test_tweets = [
    ['whats', 'up'],
    ['hello'],
    ['hey'],
    ['hi'],
    ['yo'],
    ['whatchu', 'doing'],
    ['what', 'are', 'you', 'doing'],
    ['how', 'are', 'you', 'doing'],
    ['what', 'are', 'you', 'up', 'to'],
    ['I', 'like', 'cookies'],
    ['how', 'does', 'that', 'work'],
    ['sandwich'],
    ['sadwiches'],
    ['I', 'like', 'sandwiches'],
    ['I', 'like', 'sandwich'],
    ['I', 'like', 'sandwitch'],
    ['I', 'like', 'burgers'],
]

